from __future__ import annotations

import json
import os

import psycopg

from correlation.schema import Incident, SecurityEvent
from persistence.event_repository import EventRepository
from persistence.incident_repository import IncidentRepository


DEFAULT_DATABASE_URL = os.getenv("DATABASE_URL")

if not DEFAULT_DATABASE_URL:
    raise RuntimeError("DATABASE_URL environment variable is not configured.")



class IncidentPersistenceService:
    """
    Atomically persists an Incident and all of its SecurityEvent evidence.

    Incident ID rules:

    1. If the supplied incident ID already exists in PostgreSQL,
       preserve it and update that incident.

    2. If the supplied ID is a process-generated INC-xxxxxx ID
       and does not already exist, replace it with a globally
       unique PostgreSQL sequence ID.

    3. Other caller-supplied IDs are preserved.

    All database writes use ONE PostgreSQL connection and ONE
    transaction.
    """

    def __init__(
        self,
        database_url: str = DEFAULT_DATABASE_URL,
    ) -> None:
        self.database_url = database_url

        self.incident_repository = IncidentRepository(
            database_url
        )

        self.event_repository = EventRepository()

    def _connect(self) -> psycopg.Connection:
        """
        Create the single connection used by the transaction.
        """
        return psycopg.connect(self.database_url)

    @staticmethod
    def _generate_incident_id(
        cursor,
    ) -> str:
        """
        Generate a globally unique incident ID using PostgreSQL.
        """

        cursor.execute(
            """
            SELECT nextval('incident_id_sequence')
            """
        )

        row = cursor.fetchone()

        if row is None:
            raise RuntimeError(
                "PostgreSQL did not return an incident sequence value."
            )

        incident_number = int(row[0])

        return f"INC-{incident_number:06d}"

    @staticmethod
    def _incident_exists(
        cursor,
        incident_id: str,
    ) -> bool:
        """
        Check whether an incident already exists.
        """

        cursor.execute(
            """
            SELECT 1
            FROM incidents
            WHERE incident_id = %s
            LIMIT 1
            """,
            (incident_id,),
        )

        return cursor.fetchone() is not None

    @staticmethod
    def _is_process_generated_id(
        incident_id: str,
    ) -> bool:
        """
        Determine whether an incident ID follows the process-level
        INC-000001 format generated by IncidentManager.
        """

        if not isinstance(
            incident_id,
            str,
        ):
            return False

        if not incident_id.startswith("INC-"):
            return False

        suffix = incident_id[4:]

        return (
            suffix.isdigit()
            and len(suffix) == 6
        )

    def _resolve_incident_id(
        self,
        cursor,
        incident_id: str,
    ) -> str:
        """
        Resolve the durable incident ID.

        Existing IDs are preserved.

        New process-generated IDs are replaced with IDs from the
        PostgreSQL sequence.

        Other caller-supplied IDs are preserved.
        """

        if not isinstance(
            incident_id,
            str,
        ):
            raise TypeError(
                "incident.incident_id must be a string."
            )

        incident_id = incident_id.strip()

        if not incident_id:
            raise ValueError(
                "incident.incident_id cannot be empty."
            )

        if self._incident_exists(
            cursor,
            incident_id,
        ):
            return incident_id

        if self._is_process_generated_id(
            incident_id
        ):
            return self._generate_incident_id(
                cursor
            )

        return incident_id

    def save_incident_with_events(
        self,
        incident: Incident,
    ) -> None:
        """
        Persist an incident and all of its events atomically.
        """

        if not isinstance(
            incident,
            Incident,
        ):
            raise TypeError(
                "incident must be an Incident."
            )

        events = list(incident.events)

        if not events:
            raise ValueError(
                "incident must contain at least one SecurityEvent."
            )

        self._validate_events(events)

        with self._connect() as connection:
            with connection.cursor() as cursor:

                # -------------------------------------------------
                # 1. Resolve durable incident ID
                # -------------------------------------------------

                incident.incident_id = (
                    self._resolve_incident_id(
                        cursor=cursor,
                        incident_id=incident.incident_id,
                    )
                )

                # -------------------------------------------------
                # 2. Save security events
                # -------------------------------------------------

                self._save_events(
                    cursor=cursor,
                    events=events,
                )

                # -------------------------------------------------
                # 3. Save incident
                # -------------------------------------------------

                self._save_incident(
                    cursor=cursor,
                    incident=incident,
                )

                # -------------------------------------------------
                # 4. Create incident-event relationships
                # -------------------------------------------------

                self._link_events(
                    cursor=cursor,
                    incident_id=incident.incident_id,
                    events=events,
                )

            # Leaving the connection context commits the transaction
            # if no exception occurred.

            # If any exception occurred above, psycopg rolls back.

    @staticmethod
    def _validate_events(
        events: list[SecurityEvent],
    ) -> None:
        """
        Validate the event collection.
        """

        event_ids = [
            event.event_id
            for event in events
        ]

        if len(event_ids) != len(set(event_ids)):
            raise ValueError(
                "incident contains duplicate event_id values."
            )

        for event in events:
            if not isinstance(
                event,
                SecurityEvent,
            ):
                raise TypeError(
                    "incident.events must contain only SecurityEvent objects."
                )

    @staticmethod
    def _save_events(
        cursor,
        events: list[SecurityEvent],
    ) -> None:
        """
        Persist all security events using the supplied transaction.
        """

        query = """
            INSERT INTO security_events (
                event_id,
                timestamp,
                src_ip,
                dst_ip,
                src_port,
                dst_port,
                protocol,
                protocol_name,
                binary_prediction,
                attack_family,
                confidence,
                source_file,
                true_label,
                true_attack_family,
                event_type,
                windows_event_id,
                username,
                domain,
                process_name,
                firewall_action,
                raw_log,
                metadata
            )
            VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
            )
            ON CONFLICT (event_id)
            DO UPDATE SET
                timestamp = EXCLUDED.timestamp,
                src_ip = EXCLUDED.src_ip,
                dst_ip = EXCLUDED.dst_ip,
                src_port = EXCLUDED.src_port,
                dst_port = EXCLUDED.dst_port,
                protocol = EXCLUDED.protocol,
                protocol_name = EXCLUDED.protocol_name,
                binary_prediction = EXCLUDED.binary_prediction,
                attack_family = EXCLUDED.attack_family,
                confidence = EXCLUDED.confidence,
                source_file = EXCLUDED.source_file,
                true_label = EXCLUDED.true_label,
                true_attack_family = EXCLUDED.true_attack_family,
                event_type = EXCLUDED.event_type,
                windows_event_id = EXCLUDED.windows_event_id,
                username = EXCLUDED.username,
                domain = EXCLUDED.domain,
                process_name = EXCLUDED.process_name,
                firewall_action = EXCLUDED.firewall_action,
                raw_log = EXCLUDED.raw_log,
                metadata = EXCLUDED.metadata
        """

        values = [
            EventRepository._event_to_values(event)
            for event in events
        ]

        cursor.executemany(
            query,
            values,
        )

    @staticmethod
    def _save_incident(
        cursor,
        incident: Incident,
    ) -> None:
        """
        Persist the incident using the supplied transaction.
        """

        if incident.start_time is None:
            raise ValueError(
                "incident.start_time cannot be None."
            )

        if incident.end_time is None:
            raise ValueError(
                "incident.end_time cannot be None."
            )

        if incident.primary_attack_family is None:
            raise ValueError(
                "incident.primary_attack_family cannot be None."
            )

        query = """
            INSERT INTO incidents (
                incident_id,
                start_time,
                end_time,
                severity,
                primary_family,
                confidence,
                event_count,
                source_ips,
                destination_ips,
                destination_ports,
                protocols,
                family_distribution
            )
            VALUES (
                %s, %s, %s, %s, %s, %s, %s,
                %s::jsonb,
                %s::jsonb,
                %s::jsonb,
                %s::jsonb,
                %s::jsonb
            )
            ON CONFLICT (incident_id)
            DO UPDATE SET
                start_time = EXCLUDED.start_time,
                end_time = EXCLUDED.end_time,
                severity = EXCLUDED.severity,
                primary_family = EXCLUDED.primary_family,
                confidence = EXCLUDED.confidence,
                event_count = EXCLUDED.event_count,
                source_ips = EXCLUDED.source_ips,
                destination_ips = EXCLUDED.destination_ips,
                destination_ports = EXCLUDED.destination_ports,
                protocols = EXCLUDED.protocols,
                family_distribution = EXCLUDED.family_distribution
        """

        cursor.execute(
            query,
            (
                incident.incident_id,
                incident.start_time,
                incident.end_time,
                incident.severity,
                incident.primary_attack_family,
                float(incident.confidence),
                len(incident.events),
                json.dumps(incident.src_ips),
                json.dumps(incident.dst_ips),
                json.dumps(incident.dst_ports),
                json.dumps(incident.protocols),
                json.dumps(incident.family_distribution),
            ),
        )

    @staticmethod
    def _link_events(
        cursor,
        incident_id: str,
        events: list[SecurityEvent],
    ) -> None:
        """
        Create incident-event relationships.
        """

        query = """
            INSERT INTO incident_events (
                incident_id,
                event_id
            )
            VALUES (%s, %s)
            ON CONFLICT (incident_id, event_id)
            DO NOTHING
        """

        values = [
            (
                incident_id,
                event.event_id,
            )
            for event in events
        ]

        cursor.executemany(
            query,
            values,
        )




