from dataclasses import dataclass, field
from typing import Any


@dataclass
class AgentEvidence:
    """
    Evidence supplied to the LLM investigation agent.

    Evidence is explicitly classified so the LLM can distinguish
    observed facts from retrieved knowledge.
    """

    evidence_id: str
    source: str
    description: str
    evidence_type: str
    confidence: float | None = None


@dataclass
class AgentMITRETechnique:
    """
    MITRE ATT&CK knowledge that passed the evidence evaluation layer.
    """

    technique_id: str
    technique_name: str
    relevance: str
    relevance_score: float
    reason: str


@dataclass
class LLMInvestigationInput:
    """
    Controlled input contract for the LLM investigation agent.

    The LLM receives structured incident facts and evaluated evidence.
    It does not receive unrestricted raw network traffic.
    """

    incident_id: str

    severity: str

    primary_attack_family: str | None

    attack_families: list[str]

    event_count: int

    duration_seconds: float

    confidence: float

    family_distribution: dict[str, int]

    protocols: list[int]

    destination_ports: list[int]

    source_ips: list[str]

    destination_ips: list[str]

    evidence: list[AgentEvidence] = field(
        default_factory=list
    )

    mitre_techniques: list[AgentMITRETechnique] = field(
        default_factory=list
    )

    investigation_goal: str = (
        "Determine the most likely attack behavior, "
        "evaluate the available evidence, identify relevant "
        "MITRE ATT&CK techniques, state uncertainty, and "
        "recommend the next investigation steps."
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )


@dataclass
class AgentHypothesis:
    """
    A hypothesis generated by the LLM.

    A hypothesis is not automatically treated as fact.
    """

    hypothesis: str

    supporting_evidence_ids: list[str] = field(
        default_factory=list
    )

    contradicting_evidence_ids: list[str] = field(
        default_factory=list
    )

    confidence: float = 0.0


@dataclass
class AgentTechniqueAssessment:
    """
    LLM assessment of a MITRE ATT&CK technique.

    The technique must reference an already evaluated technique
    supplied in the input.
    """

    technique_id: str

    technique_name: str

    assessment: str

    supporting_evidence_ids: list[str] = field(
        default_factory=list
    )

    confidence: float = 0.0


@dataclass
class LLMInvestigationOutput:
    """
    Structured output expected from the LLM investigation agent.

    The output is intentionally limited to investigation and
    recommendations. It cannot directly execute response actions.
    """

    incident_id: str

    summary: str

    threat_assessment: str

    hypotheses: list[AgentHypothesis] = field(
        default_factory=list
    )

    technique_assessments: list[
        AgentTechniqueAssessment
    ] = field(default_factory=list)

    evidence_gaps: list[str] = field(
        default_factory=list
    )

    next_investigation_steps: list[str] = field(
        default_factory=list
    )

    recommended_actions: list[str] = field(
        default_factory=list
    )

    confidence: float = 0.0

    uncertainty: list[str] = field(
        default_factory=list
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )